//
//  Phrases.swift
//  Yes
//
//  Created by justin casler on 2/15/25.
//

import Foundation

struct Phrases {
    static let all: [String] = [
        "compliment a stranger",
        "10 min walk with no phone",
        "read a chapter of a book",
        "smile at 3 random people today",
        "clean your room",
        "exercise today",
        "write 3 things your greatful for",
        "meditate for 5 min",
        "tell someone you appreciate them",
        "reflect on how your day is going",
        "write down a dream you have",
        "go outside your comfort zone",
        "no junk food today",
        "get 8 hrs of sleep tonight",
        "tell your parents you love them",
        "dont scroll videos today",
        "make someone laugh",
        "try something new today",
        "cook a healthy meal",
        "do one random act of kindness",
        "take a photo of something beautiful",
        "listen to your favorite song",
        "spend 30 minutes away from screens",
        "stretch for 10 minutes",
        "set 1 goal for tomorrow",
        "say yes to life",
        "say yes instead of no today",
        "fail at something today",
        "say yes to every opportunity today",
        "write down your strengths",
        "write down your weaknesses",
        "spend time outdoors in nature",
        "avoid complaining for the whole day",
        "accept that you control what happens",
        "give yourself a genuine compliment",
        "write down your worries",
        "take a cold shower today",
        "give people the benefit of doubt",
        "notice something new around you",
        "tell a friend you appreciate them",
        "enjoy a sunrise or sunset today",
        "set aside 5 minutes to stretch",
        "write something your proud of",
        "practice patience today",
        "learn something new today",
        "choose optimism for the entire day",
        "visualize your ideal future",
        "do something creative today",
        "practice forgiveness",
        "allow yourself to dream bigger",
        "delete social media for the day",
        "drink enough water today",
        "clean a small space at home",
        "call someone you miss",
        "go to bed early tonight",
        "strech for 10 min before bed",
        "let go of something you can't control",
        "do something purely for fun",
        "say no to distractions",
        "start a new habit today",
        "face a small fear",
        "do a small thing you've been avoiding",
        "appreciate silence for 5 minutes",
        "choose healthier snacks today",
        "focus on progress, not perfection",
        "start reading a new book",
        "look at old photos of good memories",
        "practice generosity today",
        "write your goals for next month",
        "write your goals for tomorrow",
        "write your goals for this year",
        "appreciate nature today",
        "let yourself be bored today",
        "no phone before bed",
        "make decisions with intention",
        "reflect on your current life",
        "spend 10 minutes in complete silence",
        "change what needs to change"
    ]
}
